# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install requests
      uses: BSFishy/pip-action@v1
      with:
        packages: requests
    - name: tunnel
      run: |
        python tunnel.py
    - name: Push directory to another repository directory
      uses: XenonMolecule/github-action-push-to-another-repository@0.1.0
      env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source-directory: out
        destination-github-username: 'therealtunge'
        destination-repository-name: 'gittunnel'
        target-branch: 'main'
